name = "coding-zhou-python"
compatibility_date = "2024-01-01"
main = "worker.ts"

[vars]
GITHUB_REPO = "zmj2301/coding-zhou-python"
GITHUB_BRANCH = "main"

account_id = "d6b8ca32610afe0fd9407736b9266cb3"

[[kv_namespaces]]
binding = "CODE_EXPLORER_KV"
id = "70cb2749fafd40fdb5b8e3140d65a414"
preview_id = "70cb2749fafd40fdb5b8e3140d65a414"
