name = "coding-zhou-python"
compatibility_date = "2024-01-01"
main = "code-explorer/worker.ts"

[vars]
GITHUB_REPO = "zmj2301/coding-zhou-python"
GITHUB_BRANCH = "main"
ECS_SERVER_URL = "http://39.107.96.165"

account_id = "d6b8ca32610afe0fd9407736b9266cb3"

[[kv_namespaces]]
binding = "CODE_EXPLORER_KV"
id = "69c61f369a764a519631b00e613f7ea6"
preview_id = "69c61f369a764a519631b00e613f7ea6"

[assets]
binding = "ASSETS"
directory = "public"